/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as DashboardImport } from './routes/_dashboard'
import { Route as DashboardWalletImport } from './routes/_dashboard/wallet'
import { Route as DashboardTradeImport } from './routes/_dashboard/trade'
import { Route as DashboardSwapImport } from './routes/_dashboard/swap'
import { Route as DashboardSettingImport } from './routes/_dashboard/setting'
import { Route as DashboardPortfolioImport } from './routes/_dashboard/portfolio'
import { Route as DashboardFaucetImport } from './routes/_dashboard/faucet'
import { Route as DashboardDashboardImport } from './routes/_dashboard/dashboard'
import { Route as DashboardBuyImport } from './routes/_dashboard/buy'
import { Route as AuthVerifyImport } from './routes/_auth/verify'
import { Route as AuthSignupImport } from './routes/_auth/signup'
import { Route as AuthResetImport } from './routes/_auth/reset'
import { Route as AuthLoginImport } from './routes/_auth/login'
import { Route as AuthAuthImport } from './routes/_auth/auth'
import { Route as DashboardStakeIndexImport } from './routes/_dashboard/stake/index'
import { Route as DashboardMarketplaceIndexImport } from './routes/_dashboard/marketplace/index'
import { Route as DashboardPropertyPropertyIdImport } from './routes/_dashboard/property/$propertyId'
import { Route as DashboardMarketplaceMarketplaceIdImport } from './routes/_dashboard/marketplace/$marketplaceId'

// Create/Update Routes

const DashboardRoute = DashboardImport.update({
  id: '/_dashboard',
  getParentRoute: () => rootRoute,
} as any)

const DashboardWalletRoute = DashboardWalletImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => DashboardRoute,
} as any)

const DashboardTradeRoute = DashboardTradeImport.update({
  id: '/trade',
  path: '/trade',
  getParentRoute: () => DashboardRoute,
} as any)

const DashboardSwapRoute = DashboardSwapImport.update({
  id: '/swap',
  path: '/swap',
  getParentRoute: () => DashboardRoute,
} as any)

const DashboardSettingRoute = DashboardSettingImport.update({
  id: '/setting',
  path: '/setting',
  getParentRoute: () => DashboardRoute,
} as any)

const DashboardPortfolioRoute = DashboardPortfolioImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => DashboardRoute,
} as any)

const DashboardFaucetRoute = DashboardFaucetImport.update({
  id: '/faucet',
  path: '/faucet',
  getParentRoute: () => DashboardRoute,
} as any)

const DashboardDashboardRoute = DashboardDashboardImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => DashboardRoute,
} as any)

const DashboardBuyRoute = DashboardBuyImport.update({
  id: '/buy',
  path: '/buy',
  getParentRoute: () => DashboardRoute,
} as any)

const AuthVerifyRoute = AuthVerifyImport.update({
  id: '/_auth/verify',
  path: '/verify',
  getParentRoute: () => rootRoute,
} as any)

const AuthSignupRoute = AuthSignupImport.update({
  id: '/_auth/signup',
  path: '/signup',
  getParentRoute: () => rootRoute,
} as any)

const AuthResetRoute = AuthResetImport.update({
  id: '/_auth/reset',
  path: '/reset',
  getParentRoute: () => rootRoute,
} as any)

const AuthLoginRoute = AuthLoginImport.update({
  id: '/_auth/login',
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const AuthAuthRoute = AuthAuthImport.update({
  id: '/_auth/auth',
  path: '/auth',
  getParentRoute: () => rootRoute,
} as any)

const DashboardStakeIndexRoute = DashboardStakeIndexImport.update({
  id: '/stake/',
  path: '/stake/',
  getParentRoute: () => DashboardRoute,
} as any)

const DashboardMarketplaceIndexRoute = DashboardMarketplaceIndexImport.update({
  id: '/marketplace/',
  path: '/marketplace/',
  getParentRoute: () => DashboardRoute,
} as any)

const DashboardPropertyPropertyIdRoute =
  DashboardPropertyPropertyIdImport.update({
    id: '/property/$propertyId',
    path: '/property/$propertyId',
    getParentRoute: () => DashboardRoute,
  } as any)

const DashboardMarketplaceMarketplaceIdRoute =
  DashboardMarketplaceMarketplaceIdImport.update({
    id: '/marketplace/$marketplaceId',
    path: '/marketplace/$marketplaceId',
    getParentRoute: () => DashboardRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_dashboard': {
      id: '/_dashboard'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof DashboardImport
      parentRoute: typeof rootRoute
    }
    '/_auth/auth': {
      id: '/_auth/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthAuthImport
      parentRoute: typeof rootRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginImport
      parentRoute: typeof rootRoute
    }
    '/_auth/reset': {
      id: '/_auth/reset'
      path: '/reset'
      fullPath: '/reset'
      preLoaderRoute: typeof AuthResetImport
      parentRoute: typeof rootRoute
    }
    '/_auth/signup': {
      id: '/_auth/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof AuthSignupImport
      parentRoute: typeof rootRoute
    }
    '/_auth/verify': {
      id: '/_auth/verify'
      path: '/verify'
      fullPath: '/verify'
      preLoaderRoute: typeof AuthVerifyImport
      parentRoute: typeof rootRoute
    }
    '/_dashboard/buy': {
      id: '/_dashboard/buy'
      path: '/buy'
      fullPath: '/buy'
      preLoaderRoute: typeof DashboardBuyImport
      parentRoute: typeof DashboardImport
    }
    '/_dashboard/dashboard': {
      id: '/_dashboard/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardDashboardImport
      parentRoute: typeof DashboardImport
    }
    '/_dashboard/faucet': {
      id: '/_dashboard/faucet'
      path: '/faucet'
      fullPath: '/faucet'
      preLoaderRoute: typeof DashboardFaucetImport
      parentRoute: typeof DashboardImport
    }
    '/_dashboard/portfolio': {
      id: '/_dashboard/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof DashboardPortfolioImport
      parentRoute: typeof DashboardImport
    }
    '/_dashboard/setting': {
      id: '/_dashboard/setting'
      path: '/setting'
      fullPath: '/setting'
      preLoaderRoute: typeof DashboardSettingImport
      parentRoute: typeof DashboardImport
    }
    '/_dashboard/swap': {
      id: '/_dashboard/swap'
      path: '/swap'
      fullPath: '/swap'
      preLoaderRoute: typeof DashboardSwapImport
      parentRoute: typeof DashboardImport
    }
    '/_dashboard/trade': {
      id: '/_dashboard/trade'
      path: '/trade'
      fullPath: '/trade'
      preLoaderRoute: typeof DashboardTradeImport
      parentRoute: typeof DashboardImport
    }
    '/_dashboard/wallet': {
      id: '/_dashboard/wallet'
      path: '/wallet'
      fullPath: '/wallet'
      preLoaderRoute: typeof DashboardWalletImport
      parentRoute: typeof DashboardImport
    }
    '/_dashboard/marketplace/$marketplaceId': {
      id: '/_dashboard/marketplace/$marketplaceId'
      path: '/marketplace/$marketplaceId'
      fullPath: '/marketplace/$marketplaceId'
      preLoaderRoute: typeof DashboardMarketplaceMarketplaceIdImport
      parentRoute: typeof DashboardImport
    }
    '/_dashboard/property/$propertyId': {
      id: '/_dashboard/property/$propertyId'
      path: '/property/$propertyId'
      fullPath: '/property/$propertyId'
      preLoaderRoute: typeof DashboardPropertyPropertyIdImport
      parentRoute: typeof DashboardImport
    }
    '/_dashboard/marketplace/': {
      id: '/_dashboard/marketplace/'
      path: '/marketplace'
      fullPath: '/marketplace'
      preLoaderRoute: typeof DashboardMarketplaceIndexImport
      parentRoute: typeof DashboardImport
    }
    '/_dashboard/stake/': {
      id: '/_dashboard/stake/'
      path: '/stake'
      fullPath: '/stake'
      preLoaderRoute: typeof DashboardStakeIndexImport
      parentRoute: typeof DashboardImport
    }
  }
}

// Create and export the route tree

interface DashboardRouteChildren {
  DashboardBuyRoute: typeof DashboardBuyRoute
  DashboardDashboardRoute: typeof DashboardDashboardRoute
  DashboardFaucetRoute: typeof DashboardFaucetRoute
  DashboardPortfolioRoute: typeof DashboardPortfolioRoute
  DashboardSettingRoute: typeof DashboardSettingRoute
  DashboardSwapRoute: typeof DashboardSwapRoute
  DashboardTradeRoute: typeof DashboardTradeRoute
  DashboardWalletRoute: typeof DashboardWalletRoute
  DashboardMarketplaceMarketplaceIdRoute: typeof DashboardMarketplaceMarketplaceIdRoute
  DashboardPropertyPropertyIdRoute: typeof DashboardPropertyPropertyIdRoute
  DashboardMarketplaceIndexRoute: typeof DashboardMarketplaceIndexRoute
  DashboardStakeIndexRoute: typeof DashboardStakeIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardBuyRoute: DashboardBuyRoute,
  DashboardDashboardRoute: DashboardDashboardRoute,
  DashboardFaucetRoute: DashboardFaucetRoute,
  DashboardPortfolioRoute: DashboardPortfolioRoute,
  DashboardSettingRoute: DashboardSettingRoute,
  DashboardSwapRoute: DashboardSwapRoute,
  DashboardTradeRoute: DashboardTradeRoute,
  DashboardWalletRoute: DashboardWalletRoute,
  DashboardMarketplaceMarketplaceIdRoute:
    DashboardMarketplaceMarketplaceIdRoute,
  DashboardPropertyPropertyIdRoute: DashboardPropertyPropertyIdRoute,
  DashboardMarketplaceIndexRoute: DashboardMarketplaceIndexRoute,
  DashboardStakeIndexRoute: DashboardStakeIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

export interface FileRoutesByFullPath {
  '': typeof DashboardRouteWithChildren
  '/auth': typeof AuthAuthRoute
  '/login': typeof AuthLoginRoute
  '/reset': typeof AuthResetRoute
  '/signup': typeof AuthSignupRoute
  '/verify': typeof AuthVerifyRoute
  '/buy': typeof DashboardBuyRoute
  '/dashboard': typeof DashboardDashboardRoute
  '/faucet': typeof DashboardFaucetRoute
  '/portfolio': typeof DashboardPortfolioRoute
  '/setting': typeof DashboardSettingRoute
  '/swap': typeof DashboardSwapRoute
  '/trade': typeof DashboardTradeRoute
  '/wallet': typeof DashboardWalletRoute
  '/marketplace/$marketplaceId': typeof DashboardMarketplaceMarketplaceIdRoute
  '/property/$propertyId': typeof DashboardPropertyPropertyIdRoute
  '/marketplace': typeof DashboardMarketplaceIndexRoute
  '/stake': typeof DashboardStakeIndexRoute
}

export interface FileRoutesByTo {
  '': typeof DashboardRouteWithChildren
  '/auth': typeof AuthAuthRoute
  '/login': typeof AuthLoginRoute
  '/reset': typeof AuthResetRoute
  '/signup': typeof AuthSignupRoute
  '/verify': typeof AuthVerifyRoute
  '/buy': typeof DashboardBuyRoute
  '/dashboard': typeof DashboardDashboardRoute
  '/faucet': typeof DashboardFaucetRoute
  '/portfolio': typeof DashboardPortfolioRoute
  '/setting': typeof DashboardSettingRoute
  '/swap': typeof DashboardSwapRoute
  '/trade': typeof DashboardTradeRoute
  '/wallet': typeof DashboardWalletRoute
  '/marketplace/$marketplaceId': typeof DashboardMarketplaceMarketplaceIdRoute
  '/property/$propertyId': typeof DashboardPropertyPropertyIdRoute
  '/marketplace': typeof DashboardMarketplaceIndexRoute
  '/stake': typeof DashboardStakeIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/_dashboard': typeof DashboardRouteWithChildren
  '/_auth/auth': typeof AuthAuthRoute
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/reset': typeof AuthResetRoute
  '/_auth/signup': typeof AuthSignupRoute
  '/_auth/verify': typeof AuthVerifyRoute
  '/_dashboard/buy': typeof DashboardBuyRoute
  '/_dashboard/dashboard': typeof DashboardDashboardRoute
  '/_dashboard/faucet': typeof DashboardFaucetRoute
  '/_dashboard/portfolio': typeof DashboardPortfolioRoute
  '/_dashboard/setting': typeof DashboardSettingRoute
  '/_dashboard/swap': typeof DashboardSwapRoute
  '/_dashboard/trade': typeof DashboardTradeRoute
  '/_dashboard/wallet': typeof DashboardWalletRoute
  '/_dashboard/marketplace/$marketplaceId': typeof DashboardMarketplaceMarketplaceIdRoute
  '/_dashboard/property/$propertyId': typeof DashboardPropertyPropertyIdRoute
  '/_dashboard/marketplace/': typeof DashboardMarketplaceIndexRoute
  '/_dashboard/stake/': typeof DashboardStakeIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | ''
    | '/auth'
    | '/login'
    | '/reset'
    | '/signup'
    | '/verify'
    | '/buy'
    | '/dashboard'
    | '/faucet'
    | '/portfolio'
    | '/setting'
    | '/swap'
    | '/trade'
    | '/wallet'
    | '/marketplace/$marketplaceId'
    | '/property/$propertyId'
    | '/marketplace'
    | '/stake'
  fileRoutesByTo: FileRoutesByTo
  to:
    | ''
    | '/auth'
    | '/login'
    | '/reset'
    | '/signup'
    | '/verify'
    | '/buy'
    | '/dashboard'
    | '/faucet'
    | '/portfolio'
    | '/setting'
    | '/swap'
    | '/trade'
    | '/wallet'
    | '/marketplace/$marketplaceId'
    | '/property/$propertyId'
    | '/marketplace'
    | '/stake'
  id:
    | '__root__'
    | '/_dashboard'
    | '/_auth/auth'
    | '/_auth/login'
    | '/_auth/reset'
    | '/_auth/signup'
    | '/_auth/verify'
    | '/_dashboard/buy'
    | '/_dashboard/dashboard'
    | '/_dashboard/faucet'
    | '/_dashboard/portfolio'
    | '/_dashboard/setting'
    | '/_dashboard/swap'
    | '/_dashboard/trade'
    | '/_dashboard/wallet'
    | '/_dashboard/marketplace/$marketplaceId'
    | '/_dashboard/property/$propertyId'
    | '/_dashboard/marketplace/'
    | '/_dashboard/stake/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  DashboardRoute: typeof DashboardRouteWithChildren
  AuthAuthRoute: typeof AuthAuthRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthResetRoute: typeof AuthResetRoute
  AuthSignupRoute: typeof AuthSignupRoute
  AuthVerifyRoute: typeof AuthVerifyRoute
}

const rootRouteChildren: RootRouteChildren = {
  DashboardRoute: DashboardRouteWithChildren,
  AuthAuthRoute: AuthAuthRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthResetRoute: AuthResetRoute,
  AuthSignupRoute: AuthSignupRoute,
  AuthVerifyRoute: AuthVerifyRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_dashboard",
        "/_auth/auth",
        "/_auth/login",
        "/_auth/reset",
        "/_auth/signup",
        "/_auth/verify"
      ]
    },
    "/_dashboard": {
      "filePath": "_dashboard.tsx",
      "children": [
        "/_dashboard/buy",
        "/_dashboard/dashboard",
        "/_dashboard/faucet",
        "/_dashboard/portfolio",
        "/_dashboard/setting",
        "/_dashboard/swap",
        "/_dashboard/trade",
        "/_dashboard/wallet",
        "/_dashboard/marketplace/$marketplaceId",
        "/_dashboard/property/$propertyId",
        "/_dashboard/marketplace/",
        "/_dashboard/stake/"
      ]
    },
    "/_auth/auth": {
      "filePath": "_auth/auth.tsx"
    },
    "/_auth/login": {
      "filePath": "_auth/login.tsx"
    },
    "/_auth/reset": {
      "filePath": "_auth/reset.tsx"
    },
    "/_auth/signup": {
      "filePath": "_auth/signup.tsx"
    },
    "/_auth/verify": {
      "filePath": "_auth/verify.tsx"
    },
    "/_dashboard/buy": {
      "filePath": "_dashboard/buy.tsx",
      "parent": "/_dashboard"
    },
    "/_dashboard/dashboard": {
      "filePath": "_dashboard/dashboard.tsx",
      "parent": "/_dashboard"
    },
    "/_dashboard/faucet": {
      "filePath": "_dashboard/faucet.tsx",
      "parent": "/_dashboard"
    },
    "/_dashboard/portfolio": {
      "filePath": "_dashboard/portfolio.tsx",
      "parent": "/_dashboard"
    },
    "/_dashboard/setting": {
      "filePath": "_dashboard/setting.tsx",
      "parent": "/_dashboard"
    },
    "/_dashboard/swap": {
      "filePath": "_dashboard/swap.tsx",
      "parent": "/_dashboard"
    },
    "/_dashboard/trade": {
      "filePath": "_dashboard/trade.tsx",
      "parent": "/_dashboard"
    },
    "/_dashboard/wallet": {
      "filePath": "_dashboard/wallet.tsx",
      "parent": "/_dashboard"
    },
    "/_dashboard/marketplace/$marketplaceId": {
      "filePath": "_dashboard/marketplace/$marketplaceId.tsx",
      "parent": "/_dashboard"
    },
    "/_dashboard/property/$propertyId": {
      "filePath": "_dashboard/property/$propertyId.tsx",
      "parent": "/_dashboard"
    },
    "/_dashboard/marketplace/": {
      "filePath": "_dashboard/marketplace/index.tsx",
      "parent": "/_dashboard"
    },
    "/_dashboard/stake/": {
      "filePath": "_dashboard/stake/index.tsx",
      "parent": "/_dashboard"
    }
  }
}
ROUTE_MANIFEST_END */
